development:
  email_from: "frames@framefox.co.nz"
  api_url: "http://dev.framefox.co.nz:3001"
  api_base_path: "/api"
  shopify_domain: "<%= ENV['remote_shopify_domain_nz'] %>"
  shopify_access_token: "<%= ENV['remote_shopify_access_token_nz'] %>"
  currency: "NZD"
  country_code: "NZ"
  country_name: "New Zealand"
  gst_rate: 0.15
  shopify_remote_store: "https://admin.shopify.com/store/framefox-plus/"
  xero_client_id: "<%= ENV['XERO_NZ_CLIENT_ID'] %>"
  xero_client_secret: "<%= ENV['XERO_NZ_CLIENT_SECRET'] %>"
  xero_tax_type: "OUTPUT2"
  xero_account_code: "200"

production:
  email_from: "frames@framefox.co.nz"
  api_url: "https://shop.framefox.co.nz"
  api_base_path: "/api"
  shopify_domain: "<%= ENV['remote_shopify_domain_nz'] %>"
  shopify_access_token: "<%= ENV['remote_shopify_access_token_nz'] %>"
  currency: "NZD"
  country_code: "NZ"
  country_name: "New Zealand"
  gst_rate: 0.15
  shopify_remote_store: "https://admin.shopify.com/store/framefox-nz-prod/"
  xero_client_id: "<%= ENV['XERO_NZ_CLIENT_ID'] %>"
  xero_client_secret: "<%= ENV['XERO_NZ_CLIENT_SECRET'] %>"
  xero_tax_type: "OUTPUT2"
  xero_account_code: "200"
