development:
  email_from: "frames@framefox.co.nz"
  api_url: "http://dev.framefox.co.nz:3001"
  api_base_path: "/api"
  shopify_domain: "<%= ENV['remote_shopify_domain_nz'] %>"
  shopify_access_token: "<%= ENV['remote_shopify_access_token_nz'] %>"
  currency: "NZD"
  country_code: "NZ"
  country_name: "New Zealand"

production:
  email_from: "frames@framefox.co.nz"
  api_url: "https://staging.framefox.co.nz"
  api_base_path: "/api"
  shopify_domain: "<%= ENV['remote_shopify_domain_nz'] %>"
  shopify_access_token: "<%= ENV['remote_shopify_access_token_nz'] %>"
  currency: "NZD"
  country_code: "NZ"
  country_name: "New Zealand"
